### ISSUE TITLE
建议把 使用须知.md 改成 readme.md

### ISSUE THREAD

**Issue by knownothingsnow** [garychowcmu/daizhigev20#1]
这样一些提示信息可以让使用这份资料的人第一眼看到。访问这个项目的人应该有很多第一次使用github。
ps: 我本来想顺手改掉之后给你发个 pr,但是不知道是不是文件体积的关系一直fork失败。🧐

**Comment by garychowcmu** [comment]
改掉啦！【当然还是保留了一个新的使用须知方便不太懂英文或者代码界的古代文献使用者～～
